
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",fa,u,v;
if(ea){var fs=require("fs"),ha=require("path");q=l?ha.dirname(q)+"/":__dirname+"/";fa=(a,b)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a};u=(a,b,c)=>{a=a.startsWith("file://")?new URL(a):ha.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);process.on("uncaughtException",
function(a){if(!(a instanceof w))throw a;});process.on("unhandledRejection",function(a){throw a;});k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof w||x("exiting due to exception: "+b);process.exit(a)};f.inspect=function(){return"[Emscripten Module object]"}}else if(da||l)l?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=f.print||console.log.bind(console),x=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var y;f.wasmBinary&&(y=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1,la="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a,b){return a?ma(B,a,b):""}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var oa,B,pa,qa,D,E,F,G,H,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();ra.unshift(a)}var I=0,xa=null,J=null;function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";x(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ya(){return K.startsWith("data:application/octet-stream;base64,")}var K;
K="demo.wasm";if(!ya()){var za=K;K=f.locateFile?f.locateFile(za,q):q+za}function Aa(){var a=K;try{if(a==K&&y)return new Uint8Array(y);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Ba(){if(!y&&(da||l)){if("function"==typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Aa()});if(u)return new Promise(function(a,b){u(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Aa()})}function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function L(a){for(;0<a.length;)a.shift()(f)}function Ca(a){var b=Da();a();Ea(b)}var Fa=0;function Ga(){for(var a=N.length-1;0<=a;--a)Ha(a);N=[];Ia=[]}var Ia=[];function Ja(){if(Fa&&Ka.Qb)for(var a=0;a<Ia.length;++a){var b=Ia[a];Ia.splice(a,1);--a;b.zc.apply(null,b.pc)}}var N=[];function Ha(a){var b=N[a];b.target.removeEventListener(b.Jb,b.kc,b.Kb);N.splice(a,1)}
function O(a){function b(d){++Fa;Ka=a;Ja();a.Mb(d);Ja();--Fa}if(a.Lb)a.kc=b,a.target.addEventListener(a.Jb,b,a.Kb),N.push(a),La||(ua.push(Ga),La=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Jb==a.Jb&&Ha(c--)}function Ma(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var La,Ka,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function P(a){a=2<a?A(a):a;return Ua[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Va(a){return 0>Ua.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Wa(a,b,c,d,e,h){Na||(Na=Q(256));a={target:P(a),Jb:h,Lb:d,Mb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Na;C(Ma(g.target),B,n+0,128);C(m,B,n+128,128);H.get(d)(e,n,b)&&g.preventDefault()},Kb:c};O(a)}
function Xa(a,b,c,d,e,h){Oa||(Oa=Q(176));a={target:P(a),Qb:!0,Jb:h,Lb:d,Mb:function(g){var m=Oa;G[m>>3]=g.timeStamp;var n=m>>2;D[n+2]=g.location;D[n+3]=g.ctrlKey;D[n+4]=g.shiftKey;D[n+5]=g.altKey;D[n+6]=g.metaKey;D[n+7]=g.repeat;D[n+8]=g.charCode;D[n+9]=g.keyCode;D[n+10]=g.which;C(g.key||"",B,m+44,32);C(g.code||"",B,m+76,32);C(g.char||"",B,m+108,32);C(g.locale||"",B,m+140,32);H.get(d)(e,m,b)&&g.preventDefault()},Kb:c};O(a)}
function Ya(a,b,c){G[a>>3]=b.timeStamp;a>>=2;D[a+2]=b.screenX;D[a+3]=b.screenY;D[a+4]=b.clientX;D[a+5]=b.clientY;D[a+6]=b.ctrlKey;D[a+7]=b.shiftKey;D[a+8]=b.altKey;D[a+9]=b.metaKey;pa[2*a+20]=b.button;pa[2*a+21]=b.buttons;D[a+11]=b.movementX;D[a+12]=b.movementY;c=Va(c);D[a+13]=b.clientX-c.left;D[a+14]=b.clientY-c.top}
function R(a,b,c,d,e,h){Pa||(Pa=Q(72));a=P(a);O({target:a,Qb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Jb:h,Lb:d,Mb:function(g){g=g||event;Ya(Pa,g,a);H.get(d)(e,Pa,b)&&g.preventDefault()},Kb:c})}function Za(a,b,c,d,e){Qa||(Qa=Q(260));O({target:a,Jb:e,Lb:d,Mb:function(h){h=h||event;var g=Qa,m=document.pointerLockElement||document.Ob||document.Xb||document.Wb;D[g>>2]=!!m;var n=m&&m.id?m.id:"";C(Ma(m),B,g+4,128);C(n,B,g+132,128);H.get(d)(20,g,b)&&h.preventDefault()},Kb:c})}
function $a(a,b,c,d,e){O({target:a,Jb:e,Lb:d,Mb:function(h){h=h||event;H.get(d)(38,0,b)&&h.preventDefault()},Kb:c})}
function ab(a,b,c,d){Ra||(Ra=Q(36));a=P(a);O({target:a,Jb:"resize",Lb:d,Mb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Ra;D[g>>2]=e.detail;D[g+4>>2]=h.clientWidth;D[g+8>>2]=h.clientHeight;D[g+12>>2]=innerWidth;D[g+16>>2]=innerHeight;D[g+20>>2]=outerWidth;D[g+24>>2]=outerHeight;D[g+28>>2]=pageXOffset;D[g+32>>2]=pageYOffset;H.get(d)(10,g,b)&&e.preventDefault()}}},Kb:c})}
function bb(a,b,c,d,e,h){Sa||(Sa=Q(1696));a=P(a);O({target:a,Qb:"touchstart"==h||"touchend"==h,Jb:h,Lb:d,Mb:function(g){for(var m,n={},t=g.touches,r=0;r<t.length;++r)m=t[r],m.Zb=m.$b=0,n[m.identifier]=m;for(r=0;r<g.changedTouches.length;++r)m=g.changedTouches[r],m.Zb=1,n[m.identifier]=m;for(r=0;r<g.targetTouches.length;++r)n[g.targetTouches[r].identifier].$b=1;t=Sa;G[t>>3]=g.timeStamp;var p=t>>2;D[p+3]=g.ctrlKey;D[p+4]=g.shiftKey;D[p+5]=g.altKey;D[p+6]=g.metaKey;p+=7;var M=Va(a),hb=0;for(r in n)if(m=
n[r],D[p]=m.identifier,D[p+1]=m.screenX,D[p+2]=m.screenY,D[p+3]=m.clientX,D[p+4]=m.clientY,D[p+5]=m.pageX,D[p+6]=m.pageY,D[p+7]=m.Zb,D[p+8]=m.$b,D[p+9]=m.clientX-M.left,D[p+10]=m.clientY-M.top,p+=13,31<++hb)break;D[t+8>>2]=hb;H.get(d)(e,t,b)&&g.preventDefault()},Kb:c})}function cb(a,b,c,d,e,h){a={target:P(a),Jb:h,Lb:d,Mb:function(g){g=g||event;H.get(d)(e,0,b)&&g.preventDefault()},Kb:c};O(a)}
function db(a,b,c,d){Ta||(Ta=Q(104));O({target:a,Qb:!0,Jb:"wheel",Lb:d,Mb:function(e){e=e||event;var h=Ta;Ya(h,e,a);G[h+72>>3]=e.deltaX;G[h+80>>3]=e.deltaY;G[h+88>>3]=e.deltaZ;D[h+96>>2]=e.deltaMode;H.get(d)(9,h,b)&&e.preventDefault()},Kb:c})}
function eb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function fb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function gb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function ib(a){a.uc=a.getExtension("WEBGL_multi_draw")}
var jb=1,kb=[],S=[],lb=[],mb=[],nb=[],T=[],ob=[],pb={};function U(a){qb||(qb=a)}function rb(a){for(var b=jb++,c=a.length;c<b;c++)a[c]=null;return b}function sb(a,b){a.Ob||(a.Ob=a.getContext,a.getContext=function(d,e){e=a.Ob(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?tb(c,b):0}function tb(a,b){var c=rb(ob),d={sc:c,attributes:b,version:b.nc,Ub:a};a.canvas&&(a.canvas.oc=d);ob[c]=d;("undefined"==typeof b.Yb||b.Yb)&&ub(d);return c}
function ub(a){a||(a=vb);if(!a.mc){a.mc=!0;var b=a.Ub;eb(b);fb(b);gb(b);b.rc=b.getExtension("EXT_disjoint_timer_query");ib(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var qb,vb,wb=["default","low-power","high-performance"],xb=[null,[],[]];function yb(a,b,c,d){for(var e=0;e<a;e++){var h=V[c](),g=h&&rb(d);h?(h.name=g,d[g]=h):U(1282);D[b+4*e>>2]=g}}
function zb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:U(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U(1280);x("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:U(1280);x("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}D[b>>2]=c}else U(1281)}function Ab(a){var b=na(a)+1,c=Q(b);C(a,B,c,b);return c}
function Bb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function W(a){var b=V.jc;if(b){var c=b.Pb[a];"number"==typeof c&&(b.Pb[a]=c=V.getUniformLocation(b,b.hc[a]+(0<c?"["+c+"]":"")));return c}U(1282)}var X=[],Y=[];function Cb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ka=!0}k(a,new w(a))}function Db(a){var b=na(a)+1,c=Eb(b);C(a,oa,c,b);return c}for(var V,Fb=new Float32Array(288),Z=0;288>Z;++Z)X[Z]=Fb.subarray(0,Z+1);var Gb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Gb.subarray(0,Z+1);
var Nb={_:function(){return 0},db:function(){return 0},eb:function(){},J:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},fa:function(a,b,c){a=P(a);if(!a)return-4;a=Va(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},fb:function(a,b,c){B.copyWithin(a,b,b+c)},Xa:function(a,b){function c(d){H.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},bb:function(){z("OOM")},L:function(a,b,c,d){Wa(a,b,c,d,12,"blur");return 0},G:function(a,b,c){a=P(a);if(!a)return-4;a.width=
b;a.height=c;return 0},M:function(a,b,c,d){Wa(a,b,c,d,13,"focus");return 0},V:function(a,b,c,d){Xa(a,b,c,d,2,"keydown");return 0},T:function(a,b,c,d){Xa(a,b,c,d,1,"keypress");return 0},U:function(a,b,c,d){Xa(a,b,c,d,3,"keyup");return 0},s:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},$:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},X:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},ca:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},ea:function(a,b,c,d){R(a,b,c,d,6,"mouseup");
return 0},O:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Ob||document.body.Xb||document.body.Wb))return-1;a=P(a);if(!a)return-4;Za(a,b,c,d,"pointerlockchange");Za(a,b,c,d,"mozpointerlockchange");Za(a,b,c,d,"webkitpointerlockchange");Za(a,b,c,d,"mspointerlockchange");return 0},N:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Ob||document.body.Xb||document.body.Wb))return-1;a=P(a);if(!a)return-4;$a(a,b,c,d,"pointerlockerror");
$a(a,b,c,d,"mozpointerlockerror");$a(a,b,c,d,"webkitpointerlockerror");$a(a,b,c,d,"mspointerlockerror");return 0},$a:function(a,b,c,d){ab(a,b,c,d);return 0},P:function(a,b,c,d){bb(a,b,c,d,25,"touchcancel");return 0},Q:function(a,b,c,d){bb(a,b,c,d,23,"touchend");return 0},R:function(a,b,c,d){bb(a,b,c,d,24,"touchmove");return 0},S:function(a,b,c,d){bb(a,b,c,d,22,"touchstart");return 0},K:function(a,b,c,d){cb(a,b,c,d,31,"webglcontextlost");return 0},I:function(a,b,c,d){cb(a,b,c,d,32,"webglcontextrestored");
return 0},W:function(a,b,c,d){a=P(a);return"undefined"!=typeof a.onwheel?(db(a,b,c,d),0):-1},B:function(a,b){b>>=2;b={alpha:!!D[b],depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:wb[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],nc:D[b+8],tc:D[b+9],Yb:D[b+10],lc:D[b+11],vc:D[b+12],wc:D[b+13]};a=P(a);return!a||b.lc?0:sb(a,b)},wa:function(a,b){a=ob[a];b=A(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&
eb(V);"OES_vertex_array_object"==b&&fb(V);"WEBGL_draw_buffers"==b&&gb(V);"WEBGL_multi_draw"==b&&ib(V);return!!a.Ub.getExtension(b)},La:function(a){a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},Ca:function(a){vb=ob[a];f.qc=V=vb&&vb.Ub;return!a||V?0:-5},Y:function(){return 52},cb:function(){return 52},ab:function(){return 70},Z:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var g=E[b>>2],m=E[b+4>>2];b+=8;for(var n=0;n<m;n++){var t=B[g+n],r=xb[a];0===t||10===t?((1===a?ia:
x)(ma(r,0)),r.length=0):r.push(t)}e+=m}E[d>>2]=e;return 0},q:function(a){V.activeTexture(a)},E:function(a,b){V.attachShader(S[a],T[b])},a:function(a,b){V.bindBuffer(a,kb[b])},A:function(a,b){V.bindFramebuffer(a,lb[b])},Oa:function(a,b){V.bindRenderbuffer(a,mb[b])},g:function(a,b){V.bindTexture(a,nb[b])},w:function(a,b,c,d){V.blendColor(a,b,c,d)},x:function(a,b){V.blendEquationSeparate(a,b)},y:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},Qa:function(a,b,c,d){V.bufferData(a,c?B.subarray(c,c+b):b,
d)},F:function(a,b,c,d){V.bufferSubData(a,b,B.subarray(d,d+c))},za:function(a){V.clear(a)},Da:function(a,b,c,d){V.clearColor(a,b,c,d)},Ba:function(a){V.clearDepth(a)},Aa:function(a){V.clearStencil(a)},h:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},hb:function(a){V.compileShader(T[a])},Ka:function(a,b,c,d,e,h,g,m){V.compressedTexImage2D(a,b,c,d,e,h,m?B.subarray(m,m+g):null)},Ia:function(){var a=rb(S),b=V.createProgram();b.name=a;b.Tb=b.Rb=b.Sb=0;b.Vb=1;S[a]=b;return a},jb:function(a){var b=rb(T);
T[b]=V.createShader(a);return b},v:function(a){V.cullFace(a)},H:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=kb[d];e&&(V.deleteBuffer(e),e.name=0,kb[d]=null)}},o:function(a,b){for(var c=0;c<a;++c){var d=D[b+4*c>>2],e=lb[d];e&&(V.deleteFramebuffer(e),e.name=0,lb[d]=null)}},p:function(a){if(a){var b=S[a];b?(V.deleteProgram(b),b.name=0,S[a]=null):U(1281)}},ba:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=mb[d];e&&(V.deleteRenderbuffer(e),e.name=0,mb[d]=null)}},n:function(a){if(a){var b=
T[a];b?(V.deleteShader(b),T[a]=null):U(1281)}},mb:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=nb[d];e&&(V.deleteTexture(e),e.name=0,nb[d]=null)}},l:function(a){V.depthFunc(a)},m:function(a){V.depthMask(!!a)},b:function(a){V.disable(a)},t:function(a){V.disableVertexAttribArray(a)},ga:function(a,b,c){V.drawArrays(a,b,c)},ha:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},ia:function(a,b,c,d){V.drawElements(a,b,c,d)},ja:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},d:function(a){V.enable(a)},
ta:function(a){V.enableVertexAttribArray(a)},u:function(a){V.frontFace(a)},Ra:function(a,b){yb(a,b,"createBuffer",kb)},Pa:function(a,b){yb(a,b,"createRenderbuffer",mb)},Ma:function(a,b){yb(a,b,"createTexture",nb)},Ea:function(a,b){return V.getAttribLocation(S[a],A(b))},c:function(a,b){zb(a,b)},Ga:function(a,b,c,d){a=V.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,B,d,b):0;c&&(D[c>>2]=b)},D:function(a,b,c){if(c)if(a>=jb)U(1281);else if(a=S[a],35716==b)a=V.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.Tb)for(b=0;b<V.getProgramParameter(a,35718);++b)a.Tb=Math.max(a.Tb,V.getActiveUniform(a,b).name.length+1);D[c>>2]=a.Tb}else if(35722==b){if(!a.Rb)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Rb=Math.max(a.Rb,V.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.Rb}else if(35381==b){if(!a.Sb)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Sb=Math.max(a.Sb,V.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.Sb}else D[c>>2]=V.getProgramParameter(a,
b);else U(1281)},gb:function(a,b,c,d){a=V.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,B,d,b):0;c&&(D[c>>2]=b)},aa:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(T[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=V.getShaderParameter(T[a],b):U(1281)},Sa:function(a){var b=pb[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ab(b.join(" "));
break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||U(1280);b=b&&Ab(b);break;case 7938:b=Ab("OpenGL ES 2.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ab(b);break;default:U(1280)}pb[a]=b}return b},C:function(a,b){b=A(b);if(a=S[a]){var c=a,d=c.Pb,e=c.ic,h;if(!d)for(c.Pb=d={},c.hc={},h=0;h<V.getProgramParameter(c,
35718);++h){var g=V.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Bb(m);n=0<n?m.slice(0,n):m;var t=c.Vb;c.Vb+=g;e[n]=[g,t];for(m=0;m<g;++m)d[t]=m,c.hc[t++]=n}c=a.Pb;d=0;e=b;h=Bb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.ic[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else U(1281);return-1},Ha:function(a){a=S[a];V.linkProgram(a);a.Pb=0;a.ic={}},z:function(a,b){V.polygonOffset(a,b)},Na:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},i:function(a,b,c,
d){V.scissor(a,b,c,d)},ib:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?D[d+4*h>>2]:-1;e+=A(D[c+4*h>>2],0>g?void 0:g)}V.shaderSource(T[a],e)},lb:function(a,b,c){V.stencilFunc(a,b,c)},ya:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},k:function(a){V.stencilMask(a)},kb:function(a,b,c){V.stencilOp(a,b,c)},xa:function(a,b,c,d){V.stencilOpSeparate(a,b,c,d)},Ja:function(a,b,c,d,e,h,g,m,n){var t=V,r=t.texImage2D;if(n){var p=m-5120;p=1==p?B:4==p?D:6==p?F:5==p||28922==p?E:qa;var M=31-Math.clz32(p.BYTES_PER_ELEMENT);
n=p.subarray(n>>M,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<M)+4-1&-4)>>M)}else n=null;r.call(t,a,b,c,d,e,h,g,m,n)},e:function(a,b,c){V.texParameteri(a,b,c)},sa:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)},Fa:function(a,b){V.uniform1i(W(a),b)},oa:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=D[c+4*e>>2];else d=D.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)},ra:function(a,b,c){if(144>=b)for(var d=
X[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)},na:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2];else d=D.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)},qa:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)},ma:function(a,b,c){if(96>=b)for(var d=Y[3*b-
1],e=0;e<3*b;e+=3)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2];else d=D.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)},pa:function(a,b,c){if(72>=b){var d=X[4*b-1],e=F;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=F.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)},la:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=D[c+4*e>>2],d[e+1]=D[c+(4*e+4)>>2],d[e+2]=D[c+(4*e+8)>>2],d[e+3]=D[c+(4*e+12)>>2];else d=D.subarray(c>>
2,c+16*b>>2);V.uniform4iv(W(a),d)},ka:function(a,b,c,d){if(18>=b){var e=X[16*b-1],h=F;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=F.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)},f:function(a){a=S[a];V.useProgram(a);V.jc=a},ua:function(a,b){V.vertexAttribDivisor(a,
b)},va:function(a,b,c,d,e,h){V.vertexAttribPointer(a,b,c,!!d,e,h)},j:function(a,b,c,d){V.viewport(a,b,c,d)},_a:function(){f.ac=a=>{0!=Hb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.ac)},Za:function(){f.fc=a=>{const b=a.clipboardData.getData("text");Ca(()=>{const c=Db(b);Ib(c)})};window.addEventListener("paste",f.fc)},Ya:function(a){f.xc=[];a=A(a);a=document.getElementById(a);f.bc=b=>{b.stopPropagation();b.preventDefault()};f.cc=b=>{b.stopPropagation();b.preventDefault()};
f.dc=b=>{b.stopPropagation();b.preventDefault()};f.ec=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.yc=c;Jb(c.length);for(let d=0;d<c.length;d++)Ca(()=>{const e=Db(c[d].name);Kb(d,e)});Lb(b.clientX,b.clientY)};a.addEventListener("dragenter",f.bc,!1);a.addEventListener("dragleave",f.cc,!1);a.addEventListener("dragover",f.dc,!1);a.addEventListener("drop",f.ec,!1)},Ua:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},pb:function(){const a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Mb()});document.body.append(a)},ob:function(){document.getElementById("_sokol_app_input_element").focus()},tb:function(a){a=A(a);f.Nb=document.getElementById(a);f.Nb||console.log("sokol_app.h: invalid target:"+a);f.Nb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},sb:function(){window.removeEventListener("beforeunload",
f.ac)},rb:function(){window.removeEventListener("paste",f.fc)},qb:function(a){a=A(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.bc);a.removeEventListener("dragleave",f.cc);a.removeEventListener("dragover",f.dc);a.removeEventListener("drop",f.ec)},r:function(){f.Nb&&f.Nb.requestPointerLock&&f.Nb.requestPointerLock()},Wa:function(a,b){if(f.Nb){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}f.Nb.style.cursor=a}},Ta:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(B.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},nb:function(){document.getElementById("_sokol_app_input_element").blur()},Va:function(a){a=A(a);const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},
da:function(){return navigator.userAgent.includes("Macintosh")?1:0}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.ub;e=ja.buffer;f.HEAP8=oa=new Int8Array(e);f.HEAP16=pa=new Int16Array(e);f.HEAP32=D=new Int32Array(e);f.HEAPU8=B=new Uint8Array(e);f.HEAPU16=qa=new Uint16Array(e);f.HEAPU32=E=new Uint32Array(e);f.HEAPF32=F=new Float32Array(e);f.HEAPF64=G=new Float64Array(e);H=f.asm.wb;sa.unshift(f.asm.vb);I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);0==I&&(null!==xa&&(clearInterval(xa),xa=null),J&&(e=J,J=null,e()))}function b(e){a(e.instance)}function c(e){return Ba().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(e,function(h){x("failed to asynchronously prepare wasm: "+h);z(h)})}var d={a:Nb};I++;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return y||"function"!=typeof WebAssembly.instantiateStreaming||ya()||K.startsWith("file://")||ea||"function"!=typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){x("wasm streaming compile failed: "+h);x("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.vb).apply(null,arguments)};
var Mb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Mb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.xb).apply(null,arguments)},Ib=f.__sapp_emsc_onpaste=function(){return(Ib=f.__sapp_emsc_onpaste=f.asm.yb).apply(null,arguments)},Hb=f.__sapp_html5_get_ask_leave_site=function(){return(Hb=f.__sapp_html5_get_ask_leave_site=f.asm.zb).apply(null,arguments)},Jb=f.__sapp_emsc_begin_drop=function(){return(Jb=f.__sapp_emsc_begin_drop=f.asm.Ab).apply(null,arguments)},Kb=f.__sapp_emsc_drop=function(){return(Kb=
f.__sapp_emsc_drop=f.asm.Bb).apply(null,arguments)},Lb=f.__sapp_emsc_end_drop=function(){return(Lb=f.__sapp_emsc_end_drop=f.asm.Cb).apply(null,arguments)};f.__sapp_emsc_invoke_fetch_cb=function(){return(f.__sapp_emsc_invoke_fetch_cb=f.asm.Db).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Eb).apply(null,arguments)};
var Q=f._malloc=function(){return(Q=f._malloc=f.asm.Fb).apply(null,arguments)},Da=f.stackSave=function(){return(Da=f.stackSave=f.asm.Gb).apply(null,arguments)},Ea=f.stackRestore=function(){return(Ea=f.stackRestore=f.asm.Hb).apply(null,arguments)},Eb=f.stackAlloc=function(){return(Eb=f.stackAlloc=f.asm.Ib).apply(null,arguments)};f.___start_em_js=40164;f.___stop_em_js=46092;var Ob;J=function Pb(){Ob||Qb();Ob||(J=Pb)};
function Rb(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=Eb(4*(c+1)),e=d>>2;a.forEach(g=>{D[e++]=Db(g)});D[e]=0;try{var h=b(c,d);Cb(h)}catch(g){g instanceof w||"unwind"==g||k(1,g)}}
function Qb(){function a(){if(!Ob&&(Ob=!0,f.calledRun=!0,!ka)){L(sa);L(ta);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Sb&&Rb(b);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();va.unshift(c)}L(va)}}var b=b||ba;if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();L(ra);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},
1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Sb=!0;f.noInitialRun&&(Sb=!1);Qb();
